ALTER TABLE COURSE
ADD CONSTRAINT CHK_Credit CHECK (Credits BETWEEN 1 AND 12);


ALTER TABLE STUDENT
ADD CONSTRAINT CHK_PersonAge CHECK ('2004-01-01' > DOB);


ALTER TABLE COURSE
ADD CONSTRAINT CHK_Level CHECK (COURSE.Level BETWEEN 1 AND 8);