CREATE VIEW VIEW_GPA AS
SELECT TAKES.PersonID, (SUM(TAKES.SecPoint * COURSE.Credits) / SUM(COURSE.Credits)) AS GPA_Upon_100
FROM TAKES, SECTION, COURSE
WHERE TAKES.SectionID = SECTION.SectionID
AND SECTION.CoCode = COURSE.CoCode
GROUP BY PersonID;


-----------------------------------------------------------------------------------------


CREATE VIEW VIEW_MATCHING_RATE AS
SELECT CoCode AS CourseCode, CoName, (COUNT(*)/(SELECT COUNT(*)
FROM SUBJECTS, COURSE
WHERE COURSE.CoCode = CourseCode
AND COURSE.CoCode = SUBJECTS.CoCode))*100 AS MatchingRate

FROM
(SELECT AREAS.Area, COURSE.CoName, COURSE.CoCode
FROM AREAS, SUBJECTS, COURSE, SECTION, TEACHES, PERSON
WHERE SECTION.SectionID = TEACHES.SectionID
AND SECTION.CoCode = COURSE.CoCode
AND TEACHES.InstID = PERSON.PersonID
AND AREAS.PersonID = PERSON.PersonID
AND SUBJECTS.CoCode = COURSE.CoCode

INTERSECT

SELECT SUBJECTS.Subject, COURSE.CoName, COURSE.CoCode
FROM AREAS, SUBJECTS, COURSE, SECTION, TEACHES, PERSON
WHERE SECTION.SectionID = TEACHES.SectionID
AND SECTION.CoCode = COURSE.CoCode
AND TEACHES.InstID = PERSON.PersonID
AND AREAS.PersonID = PERSON.PersonID
AND SUBJECTS.CoCode = COURSE.CoCode) AS X

GROUP BY CoCode, CoName;